version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: test-mateus-redis

    mysql:
      image: mysql:5.7
      container_name: test-mateus-mysql
      working_dir: /application
      volumes:
        # - .:/application
        - ./database/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=test_mateus
        - MYSQL_USER=root
        - MYSQL_PASSWORD=123
      ports:
        - "8802:3306"

    webserver:
      image: nginx:alpine
      container_name: test-mateus-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8800:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: test-mateus-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

